# Generated by Django 4.0.6 on 2022-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('product_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('shade', models.CharField(max_length=50)),
                ('texture', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('uses', models.PositiveIntegerField()),
                ('finish_date', models.DateField()),
                ('will_repurchase', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
