# Generated by Django 4.0.6 on 2022-07-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='product_amount',
            new_name='product_count',
        ),
    ]
