# Generated by Django 4.0.6 on 2022-07-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0002_rename_product_amount_bin_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uses',
            new_name='use_count',
        ),
    ]
