# Generated by Django 4.0.6 on 2022-07-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0004_alter_product_expiry_date_alter_product_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
