# Generated by Django 4.0.6 on 2022-07-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0005_alter_product_notes_alter_product_shade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='texture',
            new_name='finish',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='product_count',
        ),
        migrations.AddField(
            model_name='bin',
            name='products',
            field=models.ManyToManyField(to='siftora_app.product'),
        ),
    ]
