# Generated by Django 4.0.6 on 2022-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0006_rename_texture_product_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='_product_count',
            field=models.PositiveIntegerField(db_column='product_count', default=0),
        ),
    ]
