# Generated by Django 4.0.6 on 2022-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0008_remove_bin__product_count_alter_bin_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='bins',
            field=models.ManyToManyField(to='siftora_app.bin'),
        ),
    ]
