# Generated by Django 4.0.6 on 2022-07-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0014_alter_bin_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bins',
            field=models.ManyToManyField(blank=True, related_name='bins', to='siftora_app.bin'),
        ),
    ]
