# Generated by Django 4.0.6 on 2022-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0016_remove_product_bins_alter_bin_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='will_repurchase',
            field=models.BooleanField(default=False),
        ),
    ]
