# Generated by Django 4.0.6 on 2022-07-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0017_alter_product_use_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand', 'name']},
        ),
    ]
