# Generated by Django 4.0.6 on 2022-08-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0018_alter_bin_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='finish',
        ),
    ]
