# Generated by Django 4.0.6 on 2022-08-29 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siftora_app', '0022_alter_bin_owner_alter_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='bin',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_bins', to='siftora_app.member'),
        ),
        migrations.AddField(
            model_name='product',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_products', to='siftora_app.member'),
        ),
    ]
