# Generated by Django 4.0.6 on 2022-08-29 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siftora_app', '0023_remove_bin_owner_remove_product_owner_bin_member_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='bin',
            name='member',
        ),
        migrations.RemoveField(
            model_name='product',
            name='member',
        ),
        migrations.AddField(
            model_name='bin',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_bins', to='siftora_app.owner'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_products', to='siftora_app.owner'),
        ),
    ]
